obj-$(CONFIG_POWER_AVS)		+= avs/
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/

#Begin [ljz add the kernel power code,20200615]
obj-$(CONFIG_ZTEMT_POWER_DEBUG)	+= ztemt_power_debug/
#End   [ljz add the kernel power code,20200615]
